version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.14
    - 5.11.15
    - 5.11.16
    - 5.11.17
    - 5.11.18
    - 5.11.19
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.5
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: gtfs
    versions:
    - 2.2.4
    - 2.3.0
    - 2.4.0
    - 2.4.1
    - 2.4.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: node
    versions:
    - 15.11.0.pre.buster.pre.slim
    - 15.12.0.pre.buster.pre.slim
    - 15.13.0.pre.buster.pre.slim
    - 15.6.0.pre.buster.pre.slim
    - 15.7.0.pre.buster.pre.slim
    - 15.8.0.pre.buster.pre.slim
    - 15.9.0.pre.buster.pre.slim
